# This is a basic workflow to help you get started with Actions

name: Deploy workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_one:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Pull app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd ..
              cd pub/SR02019/github.io/
              git pull
